"""PulsePump Programme format (.yaml).

A :class:`Programme` is an ordered sequence of :class:`Block` objects. Each
block stores one cycle of float32 pressure samples and a repeat count; the
full waveform is reconstructed by tiling each cycle and concatenating the
results. The file format is YAML; :mod:`pydantic` validates it on load with
field-level errors.
"""

from __future__ import annotations

import base64
from pathlib import Path
from typing import Annotated, Literal

import numpy as np
import yaml
from pydantic import BaseModel, Field, field_validator, model_validator

from pulsepump.core.waveform import Interpolation, WaveformConfig, WaveformType

PROGRAMME_VERSION = "1.0"
"""Current file-format version written to every saved programme."""

PressureUnits = Literal["Pa", "kPa", "mmHg", "psi", "bar"]
"""Accepted pressure unit strings."""


def encode_samples(arr: np.ndarray) -> str:
    """Encode a numpy array as a base64 float32 string.

    :param arr: Array of pressure samples to encode.
    :returns: Base64-encoded ASCII string of the array cast to float32.
    """
    return base64.b64encode(arr.astype(np.float32).tobytes()).decode("ascii")


def decode_samples(b64: str) -> np.ndarray:
    """Decode a base64 float32 string back to a numpy array.

    :param b64: Base64-encoded string produced by :func:`encode_samples`.
    :returns: Float32 array of pressure samples.
    """
    return np.frombuffer(base64.b64decode(b64), dtype=np.float32)


class FunctionGeneratorSource(BaseModel):
    """Provenance record for a block generated by the function generator.

    Stores every parameter needed to reproduce the block's samples from
    :func:`pulsepump.waveform.sample`.

    :param kind: Discriminator field; always ``"function_generator"``.
    :param type: Waveform shape.
    :param bpm: Beats per minute; must be greater than zero.
    :param amplitude: Peak-to-centre displacement in the programme's pressure units.
    :param offset: DC offset in the programme's pressure units.
    :param duty: High-level fraction of the cycle, in ``[0, 1]``.
    :param symmetry: Rise/fall split, in ``[0, 1]``.
    :param phase: Phase offset in cycles, in ``[0, 1)``.
    :param sample_rate_hz: Setpoint update rate in Hz; must be greater than zero.
    :param interpolation: Interpolation mode for display.
    """

    kind: Literal["function_generator"]
    type: WaveformType
    bpm: float = Field(gt=0)
    amplitude: float
    offset: float
    duty: float = Field(ge=0.0, le=1.0)
    symmetry: float = Field(ge=0.0, le=1.0)
    phase: float = Field(ge=0.0, lt=1.0)
    sample_rate_hz: float = Field(gt=0)
    interpolation: Interpolation

    def to_waveform_config(self) -> WaveformConfig:
        """Convert to a :class:`~pulsepump.waveform.WaveformConfig` dataclass.

        :returns: Equivalent frozen dataclass for use with waveform generation functions.
        """
        return WaveformConfig(
            type=self.type,
            bpm=self.bpm,
            amplitude=self.amplitude,
            offset=self.offset,
            duty=self.duty,
            symmetry=self.symmetry,
            phase=self.phase,
            sample_rate_hz=self.sample_rate_hz,
            interpolation=self.interpolation,
        )


class OpenBFSource(BaseModel):
    """Provenance record for a block generated by an openBF simulation.

    :param kind: Discriminator field; always ``"openbf"``.
    :param model_key: Slash-separated model identifier, e.g. ``"boileau2015/cca"``.
    :param vessel: Vessel label as defined in the model YAML network section.
    :param x_fraction: Fractional axial position along the vessel, in ``[0, 1]``.
    :param bpm: Heart rate used for the simulation in beats per minute; must be greater than zero.
    """

    kind: Literal["openbf"]
    model_key: str
    vessel: str
    x_fraction: float = Field(ge=0.0, le=1.0)
    bpm: float = Field(gt=0)


BlockSource = Annotated[
    FunctionGeneratorSource | OpenBFSource,
    Field(discriminator="kind"),
]
"""Union of source types, discriminated on the ``kind`` field."""


class Block(BaseModel):
    """One repeating unit within a :class:`Programme`.

    The effective duration of a block is
    ``sample_count / programme.sampling_rate_hz * repeat_count`` seconds.

    :param name: Human-readable block name; defaults to empty string.
    :param repeat_count: Number of times to tile the cycle; must be at least 1.
    :param samples_f32_b64: Single cycle encoded as a base64 float32 byte string.
                            Must decode to a non-empty array.
    :param source: Provenance record describing how the samples were generated.
    """

    name: str = ""
    repeat_count: int = Field(ge=1)
    samples_f32_b64: str
    source: BlockSource

    @field_validator("samples_f32_b64")
    @classmethod
    def _samples_non_empty(cls, v: str) -> str:
        arr = decode_samples(v)
        if arr.size == 0:
            raise ValueError("samples_f32_b64 must decode to a non-empty array")
        return v

    @property
    def sample_count(self) -> int:
        """Number of samples in one cycle.

        :returns: Length of the decoded float32 array.
        """
        return decode_samples(self.samples_f32_b64).size


class Programme(BaseModel):
    """A PulsePump pressure programme serialised as a ``.yaml`` file.

    Contains an ordered sequence of blocks. Call :func:`decompress` to expand
    the programme into a flat float32 sample array at ``sampling_rate_hz``.

    :param version: File-format version string; defaults to :data:`PROGRAMME_VERSION`.
    :param name: Human-readable programme name.
    :param sampling_rate_hz: Target control-loop rate on the Pico in Hz; must be greater than zero.
    :param pressure_units: Physical unit of all pressure values in this programme.
    :param blocks: Ordered list of blocks; must contain at least one entry.
    """

    version: str = PROGRAMME_VERSION
    name: str
    sampling_rate_hz: float = Field(gt=0)
    pressure_units: PressureUnits
    blocks: list[Block] = Field(min_length=1)

    @model_validator(mode="after")
    def _check_block_sample_counts(self) -> Programme:
        for i, block in enumerate(self.blocks):
            if block.sample_count < 1:
                raise ValueError(f"blocks[{i}].samples_f32_b64 decoded to zero samples")
        return self

    @property
    def total_cycles(self) -> int:
        """Total number of cycle repetitions across all blocks.

        :returns: Sum of ``repeat_count`` for every block.
        """
        return sum(b.repeat_count for b in self.blocks)

    @property
    def total_duration_s(self) -> float:
        """Total programme duration in seconds.

        :returns: Sum of ``block.sample_count / sampling_rate_hz * block.repeat_count``
                  over all blocks.
        """
        return sum(b.sample_count / self.sampling_rate_hz * b.repeat_count for b in self.blocks)


def load(path: Path) -> Programme:
    """Load a programme from a YAML file.

    :param path: Path to the ``.yaml`` file.
    :returns: Validated :class:`Programme` instance.
    :raises pydantic.ValidationError: If the file content does not conform to the schema.
    """
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    return Programme.model_validate(raw)


def save(programme: Programme, path: Path) -> None:
    """Save a programme to a YAML file.

    :param programme: The programme to serialise.
    :param path: Destination path; will be created or overwritten.
    """
    path.write_text(
        yaml.dump(programme.model_dump(mode="json"), allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


class ProgrammeError(ValueError):
    """Base class for programme-related errors."""


class SamplesMissingError(ProgrammeError):
    """Raised by :func:`decompress` when a block decodes to an empty sample array."""


def decompress(programme: Programme) -> np.ndarray:
    """Expand all blocks into a contiguous float32 sample array.

    Each block's cycle is tiled by its ``repeat_count`` and the results are
    concatenated in order. This function is pure and triggers no simulation.

    :param programme: The programme to decompress.
    :returns: Float32 array of shape ``(N,)`` where
              ``N = sum(block.sample_count * block.repeat_count)`` over all blocks.
    :raises SamplesMissingError: If any block decodes to an empty array.
    """
    parts: list[np.ndarray] = []
    for i, block in enumerate(programme.blocks):
        cycle = decode_samples(block.samples_f32_b64)
        if cycle.size == 0:
            raise SamplesMissingError(f"blocks[{i}] decoded to an empty array")
        parts.append(np.tile(cycle, block.repeat_count))
    return np.concatenate(parts).astype(np.float32)
